// === SENSOR CONFIG ===
export const SENSOR_CONFIG = {
  SAMPLE_RATE_HZ: 50,
  STA_WINDOW_SEC: 1,
  LTA_WINDOW_SEC: 30,
  TRIGGER_THRESHOLD: 2.5,
  CONFIRMATION_TIMEOUT_SEC: 10,
  IMPACT_THRESHOLD_G: 3.0,
  IMMOBILITY_THRESHOLD_G: 0.1,
  IMMOBILITY_DURATION_SEC: 300, // 5 minutos
  LIGHT_THRESHOLD_LUX: 1,
} as const;

// === TIMINGS ===
export const TIMING = {
  WS_HEARTBEAT_INTERVAL_MS: 30_000,
  WS_TIMEOUT_MS: 60_000,
  WS_RECONNECT_BASE_MS: 1_000,
  WS_MAX_RECONNECT_ATTEMPTS: 5,
  ALERT_DELIVERY_TARGET_MS: 500,
  CHECKIN_FIRST_REMINDER_MIN: 5,
  CHECKIN_NO_RESPONSE_MIN: 15,
  CHECKIN_MAX_RETRIES: 3,
  LOCATION_NORMAL_INTERVAL_MS: 300_000, // 5 min
  LOCATION_ALERT_INTERVAL_MS: 30_000,   // 30 seg
  BEACON_COUNTDOWN_SEC: 30,
  BEACON_AUDIO_CYCLE_SEC: 30,
  BEACON_FLASH_CYCLE_SEC: 60,
  BEACON_BLE_INTERVAL_MS: 1_000,
  BEACON_BLE_LOW_POWER_MS: 10_000,
  BURST_SYNC_TIMEOUT_MS: 10_000,
  NOTIFICATION_SMS_TIMEOUT_SEC: 10,
  NOTIFICATION_MSG_TIMEOUT_SEC: 15,
  NOTIFICATION_RETRY_INTERVAL_MS: 30_000,
  NOTIFICATION_MAX_RETRY_MIN: 5,
} as const;

// === MESH ===
export const MESH_CONFIG = {
  MAX_TTL: 10,
  MAX_QUEUE_SIZE: 500,
  MAX_PAYLOAD_BYTES: 1024,
  HEADER_SIZE_BYTES: 31,
  CRC_SIZE_BYTES: 2,
  RETRANSMIT_DELAY_MS: 2_000,
  DISCOVERY_INTERVAL_MS: 15_000,
  DISCOVERY_FALLBACK_INTERVAL_MS: 30_000,
  DISCOVERY_TIMEOUT_MS: 300_000, // 5 min
  RECONNECT_FLUSH_TIMEOUT_MS: 60_000,
} as const;

// === STORAGE ===
export const STORAGE_CONFIG = {
  MAX_STORAGE_MB: 500,
  MAP_RADIUS_KM: 50,
  NEARBY_PERSONNEL_RADIUS_KM: 10,
  LOCATION_HISTORY_MAX_RECORDS: 500,
  LOCATION_RETENTION_DAYS: 90,
  STALE_DATA_HOURS: 72,
  GC_THRESHOLD_PERCENT: 90,
} as const;

// === BATTERY ===
export const BATTERY_CONFIG = {
  BURST_SYNC_THRESHOLD_PERCENT: 5,
  TARGET_BEACON_HOURS: 48,
} as const;

// === MESSAGE TYPES (Mesh Protocol) ===
export const MESH_MESSAGE_TYPES = {
  SOS: 0x0,
  ESTOY_BIEN: 0x1,
  UBICACION_GPS: 0x2,
  CHECK_IN: 0x3,
  ALERTA_SISMICA: 0x4,
  BALIZA_ACTIVA: 0x5,
  BURST_SYNC: 0x6,
  PEER_DISCOVERY: 0x7,
  ACK: 0x8,
  HEARTBEAT_MESH: 0x9,
  MENSAJE_TEXTO: 0xa,
} as const;

export const MAX_MESH_MESSAGE_TYPE = 0xa;
